import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { getAllEmailDrafts } from "@/lib/actions/email-drafts";
import { createClient } from "@/lib/supabase/server";
import { EmailDraftViewButton } from "./email-draft-view-button";

function statusBadge(status: string) {
  if (status === "sent") {
    return (
      <Badge className="border border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900/40 dark:bg-emerald-500/10 dark:text-emerald-300">
        Sent
      </Badge>
    );
  }
  if (status === "scheduled") {
    return (
      <Badge className="border border-blue-200 bg-blue-50 text-blue-700 dark:border-blue-900/40 dark:bg-blue-500/10 dark:text-blue-300">
        Scheduled
      </Badge>
    );
  }
  return (
    <Badge className="border border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900/40 dark:bg-amber-500/10 dark:text-amber-300">
      Draft
    </Badge>
  );
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

export default async function EmailsPage() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const userId = user?.id ?? null;
  const drafts = userId ? await getAllEmailDrafts(userId) : [];

  return (
    <div className="@container/main flex flex-1 flex-col gap-2">
      <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
        <div className="flex items-center justify-between gap-3 px-4 lg:px-6">
          <div>
            <h1 className="text-base font-semibold tracking-tight">Emails</h1>
            <p className="text-sm text-muted-foreground">
              View and manage email drafts generated by your assistant and agents.
            </p>
          </div>
        </div>

        <div className="grid gap-4 px-4 lg:px-6">
          <Card>
            <CardHeader className="border-b">
              <CardTitle>All Email Drafts</CardTitle>
            </CardHeader>
            <CardContent className="pt-0">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead>Subject</TableHead>
                    <TableHead>Tenant</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {drafts.length === 0 ? (
                    <TableRow>
                      <TableCell
                        colSpan={5}
                        className="py-10 text-center text-sm text-muted-foreground"
                      >
                        No email drafts yet. Use the assistant to chase rent or draft emails.
                      </TableCell>
                    </TableRow>
                  ) : (
                    drafts.map((draft) => (
                      <TableRow key={draft.id}>
                        <TableCell className="max-w-[250px] truncate font-medium">
                          {draft.subject}
                        </TableCell>
                        <TableCell>
                          {draft.tenant_name ?? "—"}
                        </TableCell>
                        <TableCell>{statusBadge(draft.status)}</TableCell>
                        <TableCell>{formatDate(draft.created_at)}</TableCell>
                        <TableCell className="text-right">
                          <EmailDraftViewButton subject={draft.subject} body={draft.body} />
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
